www/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::middleware('auth')->prefix('system')->group(function () {
    Route::get('/', 'DashboardController@index');
    Route::get('dashboard', 'DashboardController@index');
});

Route::middleware(['auth', 'role:admin'])->prefix('system/admin')->group(function () {
    Route::resource('users', 'UserController');

    Route::get('roles', 'RoleController@index')->middleware(['permission:role-list|role-create|role-edit|role-delete'])->name('roles.index');
    Route::get('roles/create', 'RoleController@create')->middleware(['permission:role-create'])->name('roles.create');
    Route::post('roles/create', 'RoleController@store')->middleware(['permission:role-create'])->name('roles.store');
    Route::get('roles/{id}', 'RoleController@show')->name('roles.show');
    Route::get('roles/{id}/edit', 'RoleController@edit')->middleware(['permission:role-edit'])->name('roles.edit');
    Route::patch('roles/{id}', 'RoleController@update')->middleware(['permission:role-edit'])->name('roles.update');
    Route::delete('roles/{id}', 'RoleController@destroy')->middleware(['permission:role-delete'])->name('roles.destroy');
});
Route::middleware(['auth', 'role:admin|marketing|operations'])->prefix('system/marketing')->group(function () {
    Route::resource('clients', 'ClientController');
    Route::resource('customers', 'CustomersController');
    Route::resource('ports', 'PortController');
});
Route::middleware(['auth', 'role:maintenance|admin|operations'])->prefix('system/maintenance')->group(function () {
    Route::resource('trucks', 'TruckController');
    Route::resource('chassis', 'ChassisController');
    Route::resource('truckrepairs', 'TruckRepairController');
    Route::post('chassis/{id}', 'ChassisController@update');
    Route::any('trucks/query', 'TruckController@TruckSearch')->name('truck_search');
});

Route::middleware(['auth', 'role:operations|marketing|admin'])->prefix('system/operations')->group(function () {
    Route::resource('transactions', 'TransactionController');
    Route::resource('containerTypes', 'ContainerTypeController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('payrolls', 'PayrollController');
    Route::resource('adjustments', 'AdjustmentController');

    Route::post('addTransactionExpense/{transaction_id}', 'TransactionController@addTransactionExpense')->name('add_expense');
    Route::post('updateTransactionStatus/{transaction_id}', 'TransactionController@updateTransactionStatus')->name('update_status');
    Route::post('addTransactionNote/{transaction_id}', 'TransactionController@addTransactionNote')->name('add_note');
    Route::post('addTransactionRemarks/{transaction_id}', 'TransactionController@addTransactionRemarks')->name('add_remarks');
    Route::post('removeCost/{transaction_expense_id}', 'TransactionController@removeCost')->name('remove_cost');
    Route::post('updateTransactionPreAdviceStatus/{transaction_id}', 'TransactionController@updateTransactionPreAdviceStatus')->name('update_pre_advice');
    Route::post('releaseChassis/{transaction}', 'TransactionController@releaseChassis')->name('release_chassis');
    Route::get('exportExpenseToPdf/{transaction}', 'TransactionController@exportExpenseToPdf');

    Route::get('getCustomerAddress/{customer_id}', 'TransactionController@getCustomerAddress');
    Route::get('getPortAddress/{port_id}', 'TransactionController@getPortAddress');
    Route::get('getClientCustomers/{client_id}', 'TransactionController@getClientCustomers');
    Route::get('getExpense/{expense_id}', 'ExpenseController@getExpense');
    Route::get('payrolls/pdf/{payroll_id}', 'PayrollController@printPayrollPdf');

    Route::get('transaction/payroll-pending-data', 'PayrollController@getPayrollPendingData')->name('payroll_pending_data');
    Route::get('transaction/payroll-complete-data', 'PayrollController@getPayrollCompleteData')->name('payroll_complete_data');

    Route::post('storeFuelCost', 'ExpenseController@storeFuelCost')->name('store_fuel_cost');
    Route::get('getCustomers', 'TransactionController@getCustomers');

    Route::get('transaction/on-going-data', 'TransactionController@getTransactionOngoingData')->name('transactions_ongoing_data');
    Route::get('transaction/completed-data', 'TransactionController@getTransactionCompleteData')->name('transactions_complete_data');

    Route::get('transactionsReport', 'TransactionReport@index')->name('transactions_report.index');
    Route::post('transactionsReport', 'TransactionReport@generate')->name('transactions_report.generate');
    Route::post('transactionsImport', 'TransactionReport@import')->name('transactions_report.import');
    Route::get('downloadTemplate', 'TransactionReport@downloadTemplate')->name('transactions_report.download_template');


});

Route::middleware(['auth', 'role:accountant|admin'])->prefix('system/accounting')->group(function () {
    Route::get('/', 'AccountingController@index')->name('accounting.index');
    Route::post('reportGenerator', 'AccountingController@generateReport')->name('accounting_report');

    Route::post('approveCost/{expense_id}', 'AccountingController@approveCost')->name('approve_cost');
});

Route::get('/', 'FrontController@index');

Route::middleware('auth')->prefix('search')->group(function () {
    Route::get('/', 'SearchController@search');
});

www/resources/views/users_old/create.blade.php
@extends('layouts.layout')

@section('content')
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>Add User</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('/') }}">Dashboard</a>
            </li>
            <li class="active">
                <strong>Add User</strong>
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Add User Form</h5>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal" action="{{ route('users.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group"><label class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10"><input type="text" name="name" class="form-control"></div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group"><label class="col-sm-2 control-label">Contact Number</label>
                            <div class="col-sm-10"><input type="text" name="contact_no" class="form-control"></div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group"><label class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-10"><input type="text" name="email" class="form-control"></div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group"><label class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-10"><input type="password" class="form-control" name="password"></div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group"><label class="col-sm-2 control-label">Select</label>
                            <div class="col-sm-10">
                                <select class="form-control m-b" name="user_role_id">
                                    @foreach($user_roles as $user_role)
                                        <option value="{{ $user_role->id }}">{{ $user_role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <a href="{{ route('users.index') }}" class="btn btn-white">Cancel</a>
                                <button class="btn btn-primary" type="submit">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

www/resources/views/users_old/edit.blade.php
@extends('layouts.layout')

@section('content')
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Edit User</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('/') }}">Dashboard</a>
            </li>
            <li class="active">
                <strong>Edit User</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edit User Form</h5>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal" action="{{ route('users.update', $user->id) }}">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">
                        <div class="form-group"><label class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10"><input type="text" name="name" class="form-control" value="{{ $user->name }}"></div>
                        </div>
                        <div class="form-group"><label class="col-sm-2 control-label">Contact Number</label>
                            <div class="col-sm-10"><input type="text" name="contact_no" class="form-control" value="{{ $user->contact_no }}"></div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group"><label class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-10"><input type="text" name="email" class="form-control" value="{{ $user->email }}"></div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group"><label class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-10"><input type="password" class="form-control" name="password"></div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group"><label class="col-sm-2 control-label">Select</label>
                            <div class="col-sm-10">
                                <select class="form-control m-b" name="user_role_id">
                                    @foreach($user_roles as $user_role)
                                        <option value="{{ $user_role->id }}" @if($user->role->id == $user_role->id) selected @endif>{{ $user_role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <a href="{{ route('users.index') }}" class="btn btn-white">Cancel</a>
                                <button class="btn btn-primary" type="submit">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

www/resources/views/users_old/index.blade.php
@extends('layouts.layout')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>All Users</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ url('system/dashboard') }}">Dashboard</a>
                </li>
                <li class="active">
                    <strong>User List</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Users List</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-9 m-b-xs text-left">
                                        <a href="{{ route('users.create') }}" class="btn btn-primary">Add Users</a>
                                    </div>
                                    <div class="col-md-3 text-right">
                                        <div class="input-group"><input type="text" placeholder="Search"
                                                                        class="input-sm form-control"> <span
                                                    class="input-group-btn">
                                            <button type="button" class="btn btn-sm btn-primary"> Go!</button> </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach($users as $user)
                <div class="col-lg-4">
                    <div class="contact-box">
                        <a href="{{ route('users.show', $user->id) }}">
                            <div class="col-sm-12">
                                <h3><strong>{{ $user->name }}</strong></h3>
                                <span class="">Position: {{ $user->role->name }}</span>
                            </div>
                            <div class="clearfix"></div>
                        </a>
                    </div>
                </div>
            @endforeach
        </div>

    </div>
@endsection

www/resources/views/users_old/show.blade.php
@extends('layouts.layout')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>All Users</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('users.index') }}">All Users</a>
                </li>
                <li class="active">
                    <strong>Users Profile</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content">
        <div class="row animated fadeInRight">
            <div class="col-md-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Profile Detail</h5>
                        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary btn-xs pull-right"><i
                                    class="fa fa-pencil"></i> Edit</a>
                    </div>
                    <div>
                        <div class="ibox-content profile-content">
                            <h4><strong>{{ $user->name }}</strong></h4>
                            <small class="text-muted">{{$user->role->name}}</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Activites</h5>
                    </div>
                    <div class="ibox-content">

                        <div>
                            <div class="feed-activity-list">
                                @foreach($audit_array as $audit)
                                    <div class="feed-element">
                                        <div class="media-body ">
                                            <small class="pull-right">{{$audit['created_at_ago']}}</small>
                                            <strong>{{ucfirst($audit['Type'])}} &nbsp;</strong>
                                            @if($audit['old'][0])
                                                @foreach($audit['old'][0] as $key => $item)
                                                    @if($key=='name')
                                                        {{$item}}
                                                    @elseif($key=='description')
                                                        {{$item}}
                                                    @endif
                                                @endforeach
                                                To &nbsp;
                                            @endif
                                            {{--<a href="{{$audit['url']}}">--}}
                                                @foreach($audit['new'][0] as $key => $item)
                                                    @if($key=='name')
                                                        {{$item}}
                                                    @elseif($key=='description')
                                                        {{$item}}
                                                    @endif
                                                @endforeach
                                            {{--</a>--}}
                                            <br>
                                            <small class="text-muted">{{$audit['created_at_date']}}</small>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection