www/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::middleware('auth')->prefix('system')->group(function () {
    Route::get('/', 'DashboardController@index');
    Route::get('dashboard', 'DashboardController@index');
});

Route::middleware(['auth', 'role:admin'])->prefix('system/admin')->group(function () {
    Route::resource('users', 'UserController');

    Route::get('roles', 'RoleController@index')->middleware(['permission:role-list|role-create|role-edit|role-delete'])->name('roles.index');
    Route::get('roles/create', 'RoleController@create')->middleware(['permission:role-create'])->name('roles.create');
    Route::post('roles/create', 'RoleController@store')->middleware(['permission:role-create'])->name('roles.store');
    Route::get('roles/{id}', 'RoleController@show')->name('roles.show');
    Route::get('roles/{id}/edit', 'RoleController@edit')->middleware(['permission:role-edit'])->name('roles.edit');
    Route::patch('roles/{id}', 'RoleController@update')->middleware(['permission:role-edit'])->name('roles.update');
    Route::delete('roles/{id}', 'RoleController@destroy')->middleware(['permission:role-delete'])->name('roles.destroy');
});
Route::middleware(['auth', 'role:admin|marketing|operations'])->prefix('system/marketing')->group(function () {
    Route::resource('clients', 'ClientController');
    Route::resource('customers', 'CustomersController');
    Route::resource('ports', 'PortController');
});
Route::middleware(['auth', 'role:maintenance|admin|operations'])->prefix('system/maintenance')->group(function () {
    Route::resource('trucks', 'TruckController');
    Route::resource('chassis', 'ChassisController');
    Route::resource('truckrepairs', 'TruckRepairController');
    Route::post('chassis/{id}', 'ChassisController@update');
    Route::any('trucks/query', 'TruckController@TruckSearch')->name('truck_search');
});

Route::middleware(['auth', 'role:operations|marketing|admin'])->prefix('system/operations')->group(function () {
    Route::resource('transactions', 'TransactionController');
    Route::resource('containerTypes', 'ContainerTypeController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('payrolls', 'PayrollController');
    Route::resource('adjustments', 'AdjustmentController');

    Route::post('addTransactionExpense/{transaction_id}', 'TransactionController@addTransactionExpense')->name('add_expense');
    Route::post('updateTransactionStatus/{transaction_id}', 'TransactionController@updateTransactionStatus')->name('update_status');
    Route::post('addTransactionNote/{transaction_id}', 'TransactionController@addTransactionNote')->name('add_note');
    Route::post('addTransactionRemarks/{transaction_id}', 'TransactionController@addTransactionRemarks')->name('add_remarks');
    Route::post('removeCost/{transaction_expense_id}', 'TransactionController@removeCost')->name('remove_cost');
    Route::post('updateTransactionPreAdviceStatus/{transaction_id}', 'TransactionController@updateTransactionPreAdviceStatus')->name('update_pre_advice');
    Route::post('releaseChassis/{transaction}', 'TransactionController@releaseChassis')->name('release_chassis');
    Route::get('exportExpenseToPdf/{transaction}', 'TransactionController@exportExpenseToPdf');

    Route::get('getCustomerAddress/{customer_id}', 'TransactionController@getCustomerAddress');
    Route::get('getPortAddress/{port_id}', 'TransactionController@getPortAddress');
    Route::get('getClientCustomers/{client_id}', 'TransactionController@getClientCustomers');
    Route::get('getExpense/{expense_id}', 'ExpenseController@getExpense');
    Route::get('payrolls/pdf/{payroll_id}', 'PayrollController@printPayrollPdf');

    Route::get('transaction/payroll-pending-data', 'PayrollController@getPayrollPendingData')->name('payroll_pending_data');
    Route::get('transaction/payroll-complete-data', 'PayrollController@getPayrollCompleteData')->name('payroll_complete_data');

    Route::post('storeFuelCost', 'ExpenseController@storeFuelCost')->name('store_fuel_cost');
    Route::get('getCustomers', 'TransactionController@getCustomers');

    Route::get('transaction/on-going-data', 'TransactionController@getTransactionOngoingData')->name('transactions_ongoing_data');
    Route::get('transaction/completed-data', 'TransactionController@getTransactionCompleteData')->name('transactions_complete_data');

    Route::get('transactionsReport', 'TransactionReport@index')->name('transactions_report.index');
    Route::post('transactionsReport', 'TransactionReport@generate')->name('transactions_report.generate');
    Route::post('transactionsImport', 'TransactionReport@import')->name('transactions_report.import');
    Route::get('downloadTemplate', 'TransactionReport@downloadTemplate')->name('transactions_report.download_template');


});

Route::middleware(['auth', 'role:accountant|admin'])->prefix('system/accounting')->group(function () {
    Route::get('/', 'AccountingController@index')->name('accounting.index');
    Route::post('reportGenerator', 'AccountingController@generateReport')->name('accounting_report');

    Route::post('approveCost/{expense_id}', 'AccountingController@approveCost')->name('approve_cost');
});

Route::get('/', 'FrontController@index');

Route::middleware('auth')->prefix('search')->group(function () {
    Route::get('/', 'SearchController@search');
});

www/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body class="gray-bg">
    <div id="app">
        @yield('content')
    </div>

    <!-- Mainly scripts -->
    <script src="js/jquery-2.1.1.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>

www/resources/views/layouts/error.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

www/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'WestWind Trucking System') }}</title>
    {{ Html::style('css/bootstrap.min.css') }}
    {{ Html::style('font-awesome/css/font-awesome.css') }}
    {{ Html::style('css/plugins/toastr/toastr.min.css') }}
    {{ Html::style('css/plugins/select2/select2.min.css') }}
    {{ Html::style('css/plugins/chosen/chosen.css') }}
    {{ Html::style('js/plugins/gritter/jquery.gritter.css') }}
    {{ Html::style('css/plugins/datapicker/datepicker3.css') }}
    {{ Html::style('css/plugins/dataTables/datatables.min.css') }}
    {{ Html::style('css/animate.css') }}
    {{ Html::style('css/style.css') }}
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>

<body data-url="{{url('/')}}">
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="profile-element text-white">
                        <a href="{{ route('users.show', Auth::user()->id) }}">
                        <span class="block m-t-xs"> Hi {{ Auth::user()->name }}!</span>
                        @foreach(Auth::user()->roles as $roles)
                            <span class="text-muted text-xs block">{{$roles->name}}</span>
                        @endforeach
                        </a>
                    </div>
                    <div class="logo-element">
                        WW
                    </div>
                </li>

                <li class="nav-items" data-nav-name="dashboard">
                    <a href="{{ url('system/dashboard') }}"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span></a>
                </li>

                <li class="nav-items" data-nav-name="operations">
                    <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">Operations</span><span
                                class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li class="nav-items" data-nav-name="transactions"><a href="{{ route('transactions.index') }}">Transactions</a></li>
                        <li class="nav-items" data-nav-name="containerTypes"><a href="{{ route('containerTypes.index') }}">Container Types</a></li>
                        <li class="nav-items" data-nav-name="expenses"><a href="{{ route('expenses.index') }}">Expenses</a></li>
                        <li class="nav-items" data-nav-name="payrolls"><a href="{{ route('payrolls.index') }}">Payroll</a></li>
                        <li class="nav-items" data-nav-name="transactionReport"><a href="{{ route('transactions_report.index') }}">Report</a></li>
                    </ul>
                </li>

                <li class="nav-items" data-nav-name="maintenance">
                    <a href="#"><i class="fa fa-truck"></i> <span class="nav-label">Maintenance</span><span
                                class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li class="nav-items" data-nav-name="trucks"><a href="{{ route('trucks.index') }}">Trucks</a></li>
                        <li class="nav-items" data-nav-name="chassis"><a href="{{ route('chassis.index') }}">Chassis</a></li>

                    </ul>
                </li>

                <li class="nav-items" data-nav-name="marketing">
                    <a href="#"><i class="fa fa-address-book" aria-hidden="true"></i>
                        <span class="nav-label">Marketing</span>
                        <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li class="nav-items" data-nav-name="clients">
                            <a href="{{ route('clients.index') }}"><span
                                        class="nav-label">Clients</span></a>
                        </li>
                        <li class="nav-items" data-nav-name="ports"><a
                                    href="{{ route('ports.index') }}"><span
                                        class="nav-label">Ports</span></a>
                        </li>
                    </ul>
                </li>

                <li class="nav-items" data-nav-name="acccounting">
                    <a href="#"><i class="fa fa-money"></i> <span class="nav-label">Accounting</span><span
                                class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li class="nav-items" data-nav-name="accounting"><a
                                    href="{{ route('accounting.index') }}">Accounting</a></li>
                    </ul>
                </li>

                <li class="nav-items" data-nav-name="admin">
                    <a href="#"><i class="fa fa-cogs" aria-hidden="true"></i> <span class="nav-label">Admin</span><span
                                class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li class="nav-items" data-nav-name="users"><a href="{{ route('users.index') }}">Users</a></li>
                        <li class="nav-items" data-nav-name="roles"><a href="{{ route('roles.index') }}">Roles</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i>
                    </a>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="{{ url('/logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                </ul>
            </nav>
        </div>
        <div id="content">
            @yield('content')
        </div>
        <div class="footer">
            <div>
                <strong>Copyright</strong> WestWind © 2016
            </div>
        </div>
    </div>
</div>
<!-- Mainly scripts -->
{{ Html::script('js/jquery-3.1.1.min.js') }}
{{ Html::script('js/jquery-migrate-1.4.1.min.js') }}
{{ Html::script('js/bootstrap.min.js') }}
{{ Html::script('js/plugins/metisMenu/jquery.metisMenu.js') }}
{{ Html::script('js/plugins/slimscroll/jquery.slimscroll.min.js') }}

<script src="/js/customjs/main.js"></script>

<!-- Flot -->
{{--<script src="/js/plugins/flot/jquery.flot.js"></script>--}}
{{--<script src="/js/plugins/flot/jquery.flot.tooltip.min.js"></script>--}}
{{--<script src="/js/plugins/flot/jquery.flot.spline.js"></script>--}}
{{--<script src="/js/plugins/flot/jquery.flot.resize.js"></script>--}}
{{--<script src="/js/plugins/flot/jquery.flot.pie.js"></script>--}}

<!-- Peity -->
{{--<script src="/js/plugins/peity/jquery.peity.min.js"></script>--}}
{{--<script src="/js/demo/peity-demo.js"></script>--}}

<!-- Custom and plugin javascript -->
{{ Html::script('js/inspinia.js') }}
{{ Html::script('js/plugins/pace/pace.min.js') }}

<!-- jQuery UI -->
{{--<script src="/js/plugins/jquery-ui/jquery-ui.min.js"></script>--}}

<!-- GITTER -->
{{--<script src="/js/plugins/gritter/jquery.gritter.min.js"></script>--}}

<!-- Sparkline -->
{{--<script src="/js/plugins/sparkline/jquery.sparkline.min.js"></script>--}}

<!-- Sparkline demo data  -->
{{--<script src="/js/demo/sparkline-demo.js"></script>--}}

<!-- ChartJS-->
{{--<script src="/js/plugins/chartJs/Chart.min.js"></script>--}}

<!-- Toastr -->
{{ Html::script('js/plugins/toastr/toastr.min.js') }}
{{ Html::script('js/plugins/chosen/chosen.jquery.js') }}
{{ Html::script('js/plugins/datapicker/bootstrap-datepicker.js') }}
{{ Html::script('js/plugins/dataTables/datatables.min.js') }}

{{--<script src="/js/plugins/datapicker/bootstrap-datepicker.js"></script>--}}

{{ Html::script('js/main.js') }}
@yield('scripts')
<script type="text/javascript">
    $('.nav-items').each(function(key, elem){
        var url = window.location.href;
        var target_elem = $(elem);
        if(url.indexOf(target_elem.attr('data-nav-name')) > 0){
            target_elem.addClass('active');
        }
    });
</script>
@yield('footer')

</body>

</html>