www/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::middleware('auth')->prefix('system')->group(function () {
    Route::get('/', 'DashboardController@index');
    Route::get('dashboard', 'DashboardController@index');
});

Route::middleware(['auth', 'role:admin'])->prefix('system/admin')->group(function () {
    Route::resource('users', 'UserController');

    Route::get('roles', 'RoleController@index')->middleware(['permission:role-list|role-create|role-edit|role-delete'])->name('roles.index');
    Route::get('roles/create', 'RoleController@create')->middleware(['permission:role-create'])->name('roles.create');
    Route::post('roles/create', 'RoleController@store')->middleware(['permission:role-create'])->name('roles.store');
    Route::get('roles/{id}', 'RoleController@show')->name('roles.show');
    Route::get('roles/{id}/edit', 'RoleController@edit')->middleware(['permission:role-edit'])->name('roles.edit');
    Route::patch('roles/{id}', 'RoleController@update')->middleware(['permission:role-edit'])->name('roles.update');
    Route::delete('roles/{id}', 'RoleController@destroy')->middleware(['permission:role-delete'])->name('roles.destroy');
});
Route::middleware(['auth', 'role:admin|marketing|operations'])->prefix('system/marketing')->group(function () {
    Route::resource('clients', 'ClientController');
    Route::resource('customers', 'CustomersController');
    Route::resource('ports', 'PortController');
});
Route::middleware(['auth', 'role:maintenance|admin|operations'])->prefix('system/maintenance')->group(function () {
    Route::resource('trucks', 'TruckController');
    Route::resource('chassis', 'ChassisController');
    Route::resource('truckrepairs', 'TruckRepairController');
    Route::post('chassis/{id}', 'ChassisController@update');
    Route::any('trucks/query', 'TruckController@TruckSearch')->name('truck_search');
});

Route::middleware(['auth', 'role:operations|marketing|admin'])->prefix('system/operations')->group(function () {
    Route::resource('transactions', 'TransactionController');
    Route::resource('containerTypes', 'ContainerTypeController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('payrolls', 'PayrollController');
    Route::resource('adjustments', 'AdjustmentController');

    Route::post('addTransactionExpense/{transaction_id}', 'TransactionController@addTransactionExpense')->name('add_expense');
    Route::post('updateTransactionStatus/{transaction_id}', 'TransactionController@updateTransactionStatus')->name('update_status');
    Route::post('addTransactionNote/{transaction_id}', 'TransactionController@addTransactionNote')->name('add_note');
    Route::post('addTransactionRemarks/{transaction_id}', 'TransactionController@addTransactionRemarks')->name('add_remarks');
    Route::post('removeCost/{transaction_expense_id}', 'TransactionController@removeCost')->name('remove_cost');
    Route::post('updateTransactionPreAdviceStatus/{transaction_id}', 'TransactionController@updateTransactionPreAdviceStatus')->name('update_pre_advice');
    Route::post('releaseChassis/{transaction}', 'TransactionController@releaseChassis')->name('release_chassis');
    Route::get('exportExpenseToPdf/{transaction}', 'TransactionController@exportExpenseToPdf');

    Route::get('getCustomerAddress/{customer_id}', 'TransactionController@getCustomerAddress');
    Route::get('getPortAddress/{port_id}', 'TransactionController@getPortAddress');
    Route::get('getClientCustomers/{client_id}', 'TransactionController@getClientCustomers');
    Route::get('getExpense/{expense_id}', 'ExpenseController@getExpense');
    Route::get('payrolls/pdf/{payroll_id}', 'PayrollController@printPayrollPdf');

    Route::get('transaction/payroll-pending-data', 'PayrollController@getPayrollPendingData')->name('payroll_pending_data');
    Route::get('transaction/payroll-complete-data', 'PayrollController@getPayrollCompleteData')->name('payroll_complete_data');

    Route::post('storeFuelCost', 'ExpenseController@storeFuelCost')->name('store_fuel_cost');
    Route::get('getCustomers', 'TransactionController@getCustomers');

    Route::get('transaction/on-going-data', 'TransactionController@getTransactionOngoingData')->name('transactions_ongoing_data');
    Route::get('transaction/completed-data', 'TransactionController@getTransactionCompleteData')->name('transactions_complete_data');

    Route::get('transactionsReport', 'TransactionReport@index')->name('transactions_report.index');
    Route::post('transactionsReport', 'TransactionReport@generate')->name('transactions_report.generate');
    Route::post('transactionsImport', 'TransactionReport@import')->name('transactions_report.import');
    Route::get('downloadTemplate', 'TransactionReport@downloadTemplate')->name('transactions_report.download_template');


});

Route::middleware(['auth', 'role:accountant|admin'])->prefix('system/accounting')->group(function () {
    Route::get('/', 'AccountingController@index')->name('accounting.index');
    Route::post('reportGenerator', 'AccountingController@generateReport')->name('accounting_report');

    Route::post('approveCost/{expense_id}', 'AccountingController@approveCost')->name('approve_cost');
});

Route::get('/', 'FrontController@index');

Route::middleware('auth')->prefix('search')->group(function () {
    Route::get('/', 'SearchController@search');
});

www/app/Transaction.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable;

class Transaction extends Model
{
    use SoftDeletes;
    use Auditable;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'client_id',
        'customer_id',
        'type',
        'port_id',
        'driver_id',
        'helper_id',
        'truck_id',
        'destination_address',
        'origin_address',
        'kilometer',
        'note',
        'pre_advice_status',
        'created_by_id',
        'with_vat',
        'vat_percent',
        'reference_no'
    ];

    public static $status_new = 0;
    public static $status_on_going = 1;
    public static $status_complete = 2;

    const LCL = 0;
    const FCL = 1;

    const PREADVICE_OUTSIDE_CY = 0;
    const PREADVICE_NO = 1;
    const PREADVICE_YES = 2;

    public function created_by() {
        return $this->belongsTo('App\User', 'created_by_id');
    }

    public function client() {
        return $this->belongsTo('App\Client');
    }

    public function driver() {
        return $this->belongsTo('App\User', 'driver_id');
    }

    public function helper() {
        return $this->belongsTo('App\User', 'helper_id');
    }

    public function container() {
        return $this->hasOne('App\TransactionContainer');
    }

    public function customer() {
        return $this->belongsTo('App\Customer');
    }

    public function truck() {
        return $this->belongsTo('App\Truck');
    }

    public function port() {
        return $this->belongsTo('App\Port', 'port_id');
    }

    public function transaction_expenses() {
        return $this->hasMany('App\TransactionExpense');
    }

    public function transaction_chassis() {
        return $this->hasOne('App\TransactionChassis');
    }

    public function transaction_expense_requests() {
        return $this->hasManyThrough('App\TransactionExpenseRequest', 'App\TransactionExpense');
    }

    public function transaction_notes() {
        return $this->hasMany('App\TransactionNote');
    }

    public function transaction_remarks() {
        return $this->hasMany('App\TransactionRemarks');
    }

    public function transaction_audits() {
        return $this->hasMany('App\TransactionAudit');
    }

    public function audits() {
        return $this->morphMany('App\Audit', 'auditable');
    }

    public function scopeOnGoing($query) {
        return $query->where('status', '!=', self::$status_complete);
    }

    public function scopeCompleted($query) {
        return $query->where('status', self::$status_complete);
    }

    public function scopeTransactionComplete($query) {
        return $query->where('status', self::$status_complete)->get();
    }

    public function scopeThisWeek($query) {
        return $query->whereBetween('created_at', [Carbon::now()->startOfWeek(), Carbon::now()->endOfWeek()] );
    }

    public function scopeThisMonth($query) {
        return $query->whereBetween('created_at', [Carbon::now()->startOfMonth(), Carbon::now()->endOfMonth()] );
    }

    public function scopeGetUserActiveTransaction($query, $user_id, $user_role) {
        if ($user_role == 'driver') {
            $query->where('driver_id', $user_id);
        } else if ($user_role == 'helper') {
            $query->where('helper_id', $user_id);
        } else {
            $query->where('created_by_id', $user_id);
        }

        $query->where('status', self::$status_new)->orWhere('status', self::$status_on_going);

        return $query->orderBy('created_at', 'desc')->first();
    }

    public function getStatusLabelAttribute() {
        return $this->convertStatusToText($this->status);
    }

    public function getTransportTypeAttribute() {
        return ($this->type == self::LCL) ? 'LCL' : 'FCL';
    }

    public function isFCL() {
        return ($this->type == self::FCL);
    }

    public function isLCL() {
        return ($this->type == self::LCL);
    }

    public function isComplete() {
        return ($this->status == self::$status_complete);
    }

    public function convertStatusToText($status) {
        $status_label = '';

        switch ($status) {
            case self::$status_new:
                $status_label = 'New';
                break;
            case self::$status_on_going:
                $status_label = 'On going';
                break;
            case self::$status_complete:
                $status_label = 'Complete';
                break;
        }

        return $status_label;
    }

    public function getRefNoAttribute(){
        return ($this->reference_no === null) ? $this->id : $this->reference_no;
    }

    public function getBaseEarnSalesAttribute() {
        return ($this->status != self::$status_complete) ? $this->customer->price : $this->base_earn;
    }

    public function getCurrentFuelCostAttribute() {
        if ($this->status == self::$status_complete) {
            return $this->fuel_cost;
        }

        $fuel_expense = FuelExpense::currentFuelCost();

        return (isset($fuel_expense->cost)) ? ( ceil($this->kilometer) * $fuel_expense->cost) + ( 20 * $fuel_expense->cost ) : 0;
    }

    public function getTotalVatAttribute() {
        return ($this->with_vat) ? $this->getBaseEarnSalesAttribute() * $this->vat_percent : 0.00;
    }

    public function getVatPercentageLabelAttribute(){
        return round((float) $this->vat_percent * 100 ) . '%';
    }

    public function getTotalEarnAttribute() {
        return $this->getBaseEarnSalesAttribute()
            - $this->getCurrentFuelCostAttribute()
            + $this->getTotalVatAttribute()
            + $this->transaction_expenses()->allReflectOnSales()->sum('cost')
            - $this->transaction_expenses()->allExpenseSales()->sum('cost');
    }

    public function payroll_users() {
        return $this->hasMany('App\PayrollUsers');
    }

    public function getCreatedDateAttribute() {
        return Carbon::parse($this->created_at)->format('m/d/Y');
    }
    public function getUpdatedDateAttribute() {
        return Carbon::parse($this->updated_at)->format('m/d/Y');
    }
}

www/resources/views/transactions/create.blade.php
@extends('layouts.layout')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>Add Transactions</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('transactions.index') }}">All transactions</a>
                </li>
                <li class="active">
                    <strong>Add Transactions</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Add Transaction Form</h5>
                    </div>
                    <div class="ibox-content">
                        <form method="post" class="form-horizontal" action="{{ route('transactions.store') }}">
                            {{ csrf_field() }}
                            <div class="row">
                                @include('layouts.error')
                            </div>
                            <div class="form-group"><label class="col-sm-2 control-label">Client</label>
                                <div class="col-sm-10">
                                    <select name="client_id" class="form-control">
                                        <option value="">Select Client</option>
                                        @foreach($clients as $client)
                                            <option value="{{ $client->id }}">{{ $client->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Origin</label>
                                <div class="col-sm-10">
                                    <select class="form-control" name="port_id">
                                        <option value="">Select Port Area</option>
                                        @foreach($ports as $port)
                                            <option value="{{ $port->id }}">{{ $port->name }}</option>
                                        @endforeach
                                    </select>
                                    <input type="text" name="origin_address" placeholder="Origin" class="form-control" readonly>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Customer</label>
                                <div class="col-sm-10">
                                    <select name="customer_id" class="form-control">
                                        <option value="">Select Customer</option>
                                    </select>
                                    <input type="text" name="destination_address" placeholder="Destination" class="form-control" readonly>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Driver</label>
                                <div class="col-sm-10">
                                    <select name="driver_id" class="form-control">
                                        <option value="">Select Driver</option>
                                        @foreach($drivers as $driver)
                                            <option value="{{ $driver->id }}">{{ $driver->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Helper</label>
                                <div class="col-sm-10">
                                    <select name="helper_id" class="form-control">
                                        <option value="">Select Helper</option>
                                        @foreach($helpers as $helper)
                                            <option value="{{ $helper->id }}">{{ $helper->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Truck</label>
                                <div class="col-sm-10">
                                    <select name="truck_id" class="form-control">
                                        <option value="">Select Truck</option>
                                        @foreach($trucks as $truck)
                                            <option value="{{ $truck->id }}">{{ $truck->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">With Pre-advice</label>
                                <div class="col-sm-10">
                                    <div class="col-sm-10" style="padding-top: 7px;">
                                        <input type="checkbox" name="pre_advice_status" value="{{ \App\Transaction::PREADVICE_NO }}">
                                    </div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Transport Type</label>
                                <div class="col-sm-10">
                                    <select name="type" class="form-control">
                                        <option value="{{ \App\Transaction::LCL }}">LCL</option>
                                        <option value="{{ \App\Transaction::FCL }}">FCL</option>
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group tc-container"><label class="col-sm-2 control-label">Transport Container</label>
                                <div class="col-sm-10">
                                    <input type="text" name="container_ref_id" placeholder="Container Ref#" class="form-control m-b-none">
                                    <span class="help-block m-b">If there are more than one container, separate them with forward slash (/).</span>
                                    <select class="form-control" name="container_type_id">
                                        <option value="">Select Container Type</option>
                                        @foreach($containerTypes as $containerType)
                                            <option value="{{ $containerType->id }}">{{ $containerType->name }}</option>
                                        @endforeach
                                    </select>
                                    <span class="help-block"><a href="{{ route('containerTypes.create') }}">Click here to add new container type.</a></span>
                                    <select class="form-control m-b-none" name="chassis_id">
                                        <option value="">Select Chassis</option>
                                        @foreach($chassis as $chasse)
                                            <option value="{{ $chasse->id }}">{{ $chasse->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed tc-container"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">With VAT</label>
                                <div class="col-sm-10">
                                    <div class="col-sm-10" style="padding-top: 7px;">
                                        <input type="checkbox" name="with_vat" value="1">
                                    </div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group vat-container"><label class="col-sm-2 control-label">VAT Percent</label>
                                <div class="col-sm-10">
                                    <select name="vat_percent" class="form-control">
                                        <option value=0>0%</option>
                                        <option value=0.06>6%</option>
                                        <option value=0.12>12%</option>
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed vat-container"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Note</label>
                                <div class="col-sm-10"><input type="text" name="note" class="form-control"></div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <a href="{{ route('transactions.index') }}" class="btn btn-white">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="/js/customjs/transactions.js"></script>
@endsection

www/resources/views/transactions/show_activity.blade.php
<div class="tab-pane" id="activity-tab">
    <div class="feed-activity-list">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Date</th>
                <th>User</th>
                <th>Note</th>
            </tr>
            </thead>
            <tbody>
            @forelse($transaction_note_audit as $audit)
                @if($audit->displayAudit())
                    <tr>
                        <td>{{ $audit->created_at->toDayDateTimeString() }}</td>
                        <td>{{ $audit->user->name }}</td>
                        <td>{!! $audit->displayAudit() !!}</td>
                    </tr>
                @endif
            @empty
                <tr>
                    <td class="text-center" colspan="2">No activities for this transaction</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
</div>

www/resources/views/transactions/show_detail.blade.php
<div class="row">
    <div class="col-lg-12">
        <div class="m-b-md">
            <a href="{{ route('transactions.edit', $transaction->id )}}" class="btn btn-white btn-xs pull-right">Edit
                details</a>
            <h2>Ref# {{ $transaction->ref_no }}</h2>
        </div>
        <dl class="dl-horizontal">
            <dt>Status:</dt>
            <dd>
                <span class="label label-primary" data-toggle="modal"
                      @if(!$transaction->isComplete()) data-target="#statusModal" @endif>
                    {{ $transaction->status_label }}
                </span>
                @if(!$transaction->isComplete())
                    <small>(click to change status)</small>
                @endif
            </dd>
        </dl>
    </div>
</div>
<div class="row">
    <div class="col-lg-5">
        <dl class="dl-horizontal">
            <dt>Created by:</dt>
            <dd>
                <a href="{{ route('users.show', $transaction->created_by->id) }}">{{ $transaction->created_by->name }}</a>
            </dd>
            <dt>Client:</dt>
            <dd><a href="{{ route('clients.show', $transaction->client->id) }}">{{ $transaction->client->name }}</a>
            </dd>
            <dt>Customer:</dt>
            <dd>
                <a href="{{ route('customers.show', $transaction->customer->id) }}">{{ $transaction->customer->name }}</a>
            </dd>
            <dt>Driver:</dt>
            <dd><a href="{{ route('users.show', $transaction->driver->id) }}">{{ $transaction->driver->name }}</a></dd>
            <dt>Helper:</dt>
            <dd><a href="{{ route('users.show', $transaction->helper->id) }}">{{ $transaction->helper->name }}</a></dd>
            <dt>Truck:</dt>
            <dd><a href="{{ route('trucks.show', $transaction->truck->id) }}">{{ $transaction->truck->name }}</a></dd>
            <dt>Transport type:</dt>
            <dd>  {{ $transaction->transport_type }}</dd>
        </dl>
    </div>
    <div class="col-lg-7" id="cluster_info">
        <dl class="dl-horizontal">
            @if($transaction->container)
                <dt>Container Ref#:</dt>
                <dd>  {{ $transaction->container->container_ref_id }}</dd>
                <dt>Container type:</dt>
                <dd>
                    <a href="{{ route('containerTypes.show', $transaction->container->containerType->id) }}">{{ $transaction->container->containerType->name }}</a>
                </dd>
                @if($transaction->isComplete())
                    @if(!empty($transaction->transaction_chassis))
                        @if($transaction->transaction_chassis->status == \App\TransactionChassis::ON_USE)
                            <dt>Chassis:</dt>
                            <dd>{{ $transaction->transaction_chassis->chassis->name }} <a href="#" class="btn btn-primary btn-xs" data-toggle="modal"
                                   data-target="#releaseChassis">Release</a></dd>
                        @else
                            <dt>Chassis:</dt>
                            <dd>{{ $transaction->transaction_chassis->chassis->name }} (Released at {{ $transaction->transaction_chassis->updated_at->toDateString() }})</dd>
                        @endif
                    @endif
                @else

                    @if(!empty($transaction->transaction_chassis))
                        <dt>Chassis:</dt>
                        <dd>{{ @$transaction->transaction_chassis->chassis->name }}</dd>
                    @endif
                @endif
            @endif
            <dt>Origin:</dt>
            <dd>{{ $transaction->origin_address }}</dd>
            <dt>Destination:</dt>
            <dd>{{ $transaction->destination_address }}</dd>
            <dt>Last Updated:</dt>
            <dd>{{ $transaction->updated_at->toDayDateTimeString() }}</dd>
            <dt>Created:</dt>
            <dd>{{ $transaction->created_at->toDayDateTimeString() }}</dd>
            @if($transaction->pre_advice_status != \App\Transaction::PREADVICE_OUTSIDE_CY)
                <dt>Pre-advice:</dt>
                <dd>
                    <form action="{{ route('update_pre_advice', $transaction->id) }}" method="post">
                        {{ csrf_field() }}
                        @if($transaction->pre_advice_status == \App\Transaction::PREADVICE_NO)
                            <input type="hidden" name="pre_advice_status" value="{{ \App\Transaction::PREADVICE_YES }}">
                            <button type="submit" class="btn btn-warning btn-xs change-preadvice-status">No</button>
                        @else
                            <input type="hidden" name="pre_advice_status" value="{{ \App\Transaction::PREADVICE_NO }}">
                            <button type="submit" class="btn btn-primary btn-xs change-preadvice-status">Yes</button>
                        @endif
                    </form>
                </dd>
            @endif
        </dl>
    </div>
    @if(!empty($transaction->note))
        <div class="col-lg-12">
            <dl class="dl-horizontal">
                <dt>Note:</dt>
                <dd>{{ $transaction->note }}</dd>
            </dl>
        </div>
    @endif
</div>

www/resources/views/transactions/show_sales.blade.php
<div class="tab-pane" id="sales-tab">
    <div class="feed-activity-list">
        <div class="row">
            <div class="col-xs-offset-1 col-xs-3"><h3>Sales</h3></div>
        </div>

        <div class="row">
            <div class="col-xs-offset-1 col-xs-3">Base Charge</div>
            <div class="col-xs-3"><span style="color: green;">+ ₱ {{ number_format($transaction->base_earn_sales, 2) }}</span></div>
        </div>
        <div class="row">
            <div class="col-xs-offset-1 col-xs-3"><a href="{{ route('expenses.index') . '#fuel-expense-tab' }}">Fuel Expense ({{ $transaction->kilometer }} km / {{ ceil($transaction->kilometer) }} litre)</a></div>
            <div class="col-xs-3"><span style="color: red;">- ₱ {{ number_format($transaction->current_fuel_cost, 2)}}</span></div>
        </div>
        @foreach($transaction->transaction_expenses as $expense)
            @if($expense->liquidation_status == \App\TransactionExpense::STATUS_APPROVED)
                <div class="row">
                    <div class="col-xs-offset-1 col-xs-3">{{ $expense->title }}</div>
                    <div class="col-xs-3">{!! $expense->cost_sales !!}</div>
                </div>
            @endif
        @endforeach
        @if($transaction->with_vat)
            <div class="row">
                <div class="col-xs-offset-1 col-xs-3">Base Charge VAT ({{ $transaction->vat_percentage_label }})</div>
                <div class="col-xs-3"><span style="color: green;">+ ₱ {{ number_format($transaction->total_vat, 2) }}</span></div>
            </div>
        @endif
        <div class="row">
            <div class="col-xs-offset-1 col-xs-6"><hr></div>
        </div>
        <div class="row">
            <div class="col-xs-offset-1 col-xs-3">Total</div>
            <div class="col-xs-3">&nbsp; ₱ {{ number_format($transaction->total_earn, 2) }}</div>
        </div>
    </div>
</div>