www/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::middleware('auth')->prefix('system')->group(function () {
    Route::get('/', 'DashboardController@index');
    Route::get('dashboard', 'DashboardController@index');
});

Route::middleware(['auth', 'role:admin'])->prefix('system/admin')->group(function () {
    Route::resource('users', 'UserController');

    Route::get('roles', 'RoleController@index')->middleware(['permission:role-list|role-create|role-edit|role-delete'])->name('roles.index');
    Route::get('roles/create', 'RoleController@create')->middleware(['permission:role-create'])->name('roles.create');
    Route::post('roles/create', 'RoleController@store')->middleware(['permission:role-create'])->name('roles.store');
    Route::get('roles/{id}', 'RoleController@show')->name('roles.show');
    Route::get('roles/{id}/edit', 'RoleController@edit')->middleware(['permission:role-edit'])->name('roles.edit');
    Route::patch('roles/{id}', 'RoleController@update')->middleware(['permission:role-edit'])->name('roles.update');
    Route::delete('roles/{id}', 'RoleController@destroy')->middleware(['permission:role-delete'])->name('roles.destroy');
});
Route::middleware(['auth', 'role:admin|marketing|operations'])->prefix('system/marketing')->group(function () {
    Route::resource('clients', 'ClientController');
    Route::resource('customers', 'CustomersController');
    Route::resource('ports', 'PortController');
});
Route::middleware(['auth', 'role:maintenance|admin|operations'])->prefix('system/maintenance')->group(function () {
    Route::resource('trucks', 'TruckController');
    Route::resource('chassis', 'ChassisController');
    Route::resource('truckrepairs', 'TruckRepairController');
    Route::post('chassis/{id}', 'ChassisController@update');
    Route::any('trucks/query', 'TruckController@TruckSearch')->name('truck_search');
});

Route::middleware(['auth', 'role:operations|marketing|admin'])->prefix('system/operations')->group(function () {
    Route::resource('transactions', 'TransactionController');
    Route::resource('containerTypes', 'ContainerTypeController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('payrolls', 'PayrollController');
    Route::resource('adjustments', 'AdjustmentController');

    Route::post('addTransactionExpense/{transaction_id}', 'TransactionController@addTransactionExpense')->name('add_expense');
    Route::post('updateTransactionStatus/{transaction_id}', 'TransactionController@updateTransactionStatus')->name('update_status');
    Route::post('addTransactionNote/{transaction_id}', 'TransactionController@addTransactionNote')->name('add_note');
    Route::post('addTransactionRemarks/{transaction_id}', 'TransactionController@addTransactionRemarks')->name('add_remarks');
    Route::post('removeCost/{transaction_expense_id}', 'TransactionController@removeCost')->name('remove_cost');
    Route::post('updateTransactionPreAdviceStatus/{transaction_id}', 'TransactionController@updateTransactionPreAdviceStatus')->name('update_pre_advice');
    Route::post('releaseChassis/{transaction}', 'TransactionController@releaseChassis')->name('release_chassis');
    Route::get('exportExpenseToPdf/{transaction}', 'TransactionController@exportExpenseToPdf');

    Route::get('getCustomerAddress/{customer_id}', 'TransactionController@getCustomerAddress');
    Route::get('getPortAddress/{port_id}', 'TransactionController@getPortAddress');
    Route::get('getClientCustomers/{client_id}', 'TransactionController@getClientCustomers');
    Route::get('getExpense/{expense_id}', 'ExpenseController@getExpense');
    Route::get('payrolls/pdf/{payroll_id}', 'PayrollController@printPayrollPdf');

    Route::get('transaction/payroll-pending-data', 'PayrollController@getPayrollPendingData')->name('payroll_pending_data');
    Route::get('transaction/payroll-complete-data', 'PayrollController@getPayrollCompleteData')->name('payroll_complete_data');

    Route::post('storeFuelCost', 'ExpenseController@storeFuelCost')->name('store_fuel_cost');
    Route::get('getCustomers', 'TransactionController@getCustomers');

    Route::get('transaction/on-going-data', 'TransactionController@getTransactionOngoingData')->name('transactions_ongoing_data');
    Route::get('transaction/completed-data', 'TransactionController@getTransactionCompleteData')->name('transactions_complete_data');

    Route::get('transactionsReport', 'TransactionReport@index')->name('transactions_report.index');
    Route::post('transactionsReport', 'TransactionReport@generate')->name('transactions_report.generate');
    Route::post('transactionsImport', 'TransactionReport@import')->name('transactions_report.import');
    Route::get('downloadTemplate', 'TransactionReport@downloadTemplate')->name('transactions_report.download_template');


});

Route::middleware(['auth', 'role:accountant|admin'])->prefix('system/accounting')->group(function () {
    Route::get('/', 'AccountingController@index')->name('accounting.index');
    Route::post('reportGenerator', 'AccountingController@generateReport')->name('accounting_report');

    Route::post('approveCost/{expense_id}', 'AccountingController@approveCost')->name('approve_cost');
});

Route::get('/', 'FrontController@index');

Route::middleware('auth')->prefix('search')->group(function () {
    Route::get('/', 'SearchController@search');
});

www/app/Expense.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable;

class Expense extends Model
{
    use SoftDeletes;
    use Auditable;

    protected $dates = ['deleted_at'];

    protected $fillable = ['title', 'cost', 'default', 'description'];

    public function getDefaultTextAttribute(){
        return ($this->default == 1) ? 'Yes' : 'No';
    }

    public function scopeDefault($query){
        $query->where('default', '1');
    }
}

www/resources/views/expenses/create.blade.php
@extends('layouts.layout')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>Add Expense Type</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('expenses.index') }}">All Expenses</a>
                </li>
                <li class="active">
                    <strong>Add Expense Type</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Add Expense Type Form</h5>
                    </div>
                    <div class="ibox-content">
                        @include('layouts.error')
                        <form method="post" class="form-horizontal" action="{{ route('expenses.store') }}">
                            {{ csrf_field() }}
                            <div class="form-group"><label class="col-sm-2 control-label">Title</label>
                                <div class="col-sm-10"><input type="text" name="title" class="form-control" value="{{old('title')}}"></div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Default Cost</label>
                                <div class="col-sm-10"><input type="text" name="cost" class="form-control"value="{{old('cost')}}"></div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Default</label>
                                <div class="col-sm-10" style="padding-top: 7px;">
                                    <input type="checkbox" name="default" value="1">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Description</label>
                                <div class="col-sm-10"><input type="text" name="description"
                                                              class="form-control input-lg" value="{{old('desciption')}}"></div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <a href="{{ route('trucks.index') }}" class="btn btn-white">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

www/resources/views/expenses/edit.blade.php
@extends('layouts.layout')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>Edi Expense Type</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ url('/') }}">Dashboard</a>
                </li>
                <li class="active">
                    <strong>Edit Expense Type</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Edit Expense Type Form</h5>
                    </div>
                    <div class="ibox-content">
                        @include('layouts.error')
                        <form method="post" class="form-horizontal" action="{{ route('expenses.update', $expense->id) }}">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group"><label class="col-sm-2 control-label">Title</label>
                                <div class="col-sm-10">
                                    <input type="text" value="{{ $expense->title }}" name="title" class="form-control">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Default Cost</label>
                                <div class="col-sm-10">
                                    <input type="text" value="{{ $expense->cost }}" name="cost" class="form-control">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Default</label>
                                <div class="col-sm-10" style="padding-top: 7px;">
                                    <input type="checkbox" @if($expense->default) checked @endif name="default" value="1">
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">Description</label>
                                <div class="col-sm-10"><input type="text" value="{{ $expense->description }}" name="description" class="form-control input-lg"></div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <a href="{{ route('trucks.index') }}" class="btn btn-white">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

www/resources/views/expenses/index.blade.php
@extends('layouts.layout')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-12">
            <h2>All Expense Types</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ url('system/dashboard') }}">Dashboard</a>
                </li>
                <li class="active">
                    <strong>Expense Type List</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <div class="tabs-container tab-container">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true"> <i
                                    class="fa fa-truck"></i>Transaction Expense</a></li>
                    <li><a data-toggle="tab" href="#fuel-expense-tab" aria-expanded="true"> <i class="fa fa-truck"></i>Fuel
                            Cost</a></li>
                </ul>
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-9 m-b-xs text-left">
                                        <div class="row">
                                            <a href="{{ route('expenses.create') }}" class="btn btn-primary btn-xs">Add
                                                Expense Type</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID#</th>
                                        <th>Title</th>
                                        <th>Cost</th>
                                        <th>Default</th>
                                        <th>Description</th>
                                        <th>Date Added</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($expenses as $expense)
                                        <tr>
                                            <td>{{ $expense->id }}</td>
                                            <td>
                                                <a href="{{ route('expenses.edit', $expense->id) }}">{{ $expense->title }}</a>
                                            </td>
                                            <td>{{ $expense->cost }}</td>
                                            <td>{{ $expense->default_text }}</td>
                                            <td>{{ $expense->description }}</td>
                                            <td>{{ $expense->created_at->toDayDateTimeString() }}</td>
                                            <td>
                                                <a class="btn btn-xs btn-info"
                                                   href="{{ route('expenses.edit', $expense->id) }}">Edit</a>
                                                <a class="btn btn-xs btn-danger delete-expense modal-toggle"
                                                   data-modal-target="#deleteExpense"
                                                   data-action="{{ route('expenses.destroy', $expense->id) }}" href="#">Delete</a>
                                            </td>
                                        </tr>
                                        {{--@empty--}}
                                        {{--<tr>--}}
                                        {{--<td class="text-center" colspan="7">No expense type registered.</td>--}}
                                        {{--</tr>--}}
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            {{--<div class="row text-center">--}}
                            {{--{{ $expenses->links() }}--}}
                            {{--</div>--}}
                        </div>
                    </div>
                    @include('expenses.index_fuel_expense')
                </div>
            </div>
        </div>
    </div>
    @include('expenses.index_delete_expense')
@endsection

www/resources/views/expenses/index_delete_expense.blade.php
<div class="modal fade" id="deleteExpense" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form class="form-horizontal" role="form" method="post" action="">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Delete Expense</h4>
                </div>
                <div class="modal-body" id="addExpenseContainer">
                    <h3>Are you sure you want to delete this expense?</h3>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Delete Expense</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </form>
    </div>
</div>

www/resources/views/expenses/index_fuel_expense.blade.php
<div id="fuel-expense-tab" class="tab-pane">
    <div class="panel-body">
        <form method="post" class="form-horizontal" action="{{ route('store_fuel_cost') }}">
            {{ csrf_field() }}
            <div class="form-group"><label class="col-sm-3 control-label">Current Fuel Cost Per Litre:</label>
                <div class="col-sm-4 input-group"><span class="input-group-addon">₱</span><input type="text" name="cost" class="form-control" value="{{ $currentFuelExpense->cost or 0 }}"></div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group"><label class="col-sm-3 control-label">Last Updated By:</label>
                <div class="col-sm-4 input-group"><input type="text" name="cost" class="form-control" disabled value="{{ $currentFuelExpense->user->name or "" }}"></div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-2">
                    <button class="btn btn-primary" type="submit">Update</button>
                </div>
            </div>
        </form>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>User</th>
                    <th>Cost</th>
                </tr>
                </thead>
                <tbody>
                @forelse($fuel_expenses as $fuel_expense)
                    <tr>
                        <td>{{ $fuel_expense->created_at->toDayDateTimeString() }}</td>
                        <td>{{ $fuel_expense->user->name }}</td>
                        <td>₱ {{ $fuel_expense->cost }}</td>
                    </tr>
                @empty
                    <tr>
                        <td class="text-center" colspan="3">No Fuel expense registered.</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
        {{--<div class="row text-center">--}}
            {{--{{ $fuel_expenses->links() }}--}}
        {{--</div>--}}
    </div>
</div>